//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneOff.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte Rating { get; set; }
        public string PostalCode { get; set; }
        public int RequestId { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
