//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneOff.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int ArtistId { get; set; }
        public string Name { get; set; }
        public byte Rating { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int TourId { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
