//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneOff.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Offer { get; set; }
        public int VenueId { get; set; }
    
        public virtual Venue Venue { get; set; }
    }
}
